#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/../..
basedir=$PWD
[ -e configure ] || ./autogen.sh
cd memtrace/python
mtdir=$PWD
mkdir -p build/tracer
cd build/tracer
[ -e Makefile ] || "$basedir"/configure --prefix="$mtdir/build/tracer/install"
nproc=$(getconf _NPROCESSORS_ONLN)
make -j"$nproc"
make -j"$nproc" install
cd "$mtdir"
mkdir -p memtrace/tracer
(cd build/tracer/install && tar -c \
     bin/valgrind \
     lib/valgrind/memtrace-* \
     lib/valgrind/vgpreload_core-*.so \
    ) | tar -C memtrace/tracer -xv
for python in cp36-cp36m cp37-cp37m cp38-cp38; do
    /opt/python/"$python"/bin/python -m venv "$python"
    . "$python"/bin/activate
    pip --disable-pip-version-check install -r requirements.txt
    python setup.py bdist_wheel
    set +u; deactivate; set -u
done
for whl in dist/*.whl; do
    auditwheel repair --wheel-dir=dist/wheelhouse "$whl"
done
