#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"/../..
basedir=$PWD
[ -e configure ] || ./autogen.sh
cd memtrace/python
mtdir=$PWD
mkdir -p tracer-build
cd tracer-build
[ -e Makefile ] || "$basedir"/configure --prefix="$mtdir/tracer"
nproc=$(getconf _NPROCESSORS_ONLN)
make -j"$nproc"
make -j"$nproc" install
cd "$mtdir"
tar -c tracer/bin/valgrind tracer/lib/valgrind/{memtrace-*,vgpreload_core-*.so} | tar -C memtrace -xv
for i in "py36 /opt/python/cp36-cp36m/bin/python" \
         "py37 /opt/python/cp37-cp37m/bin/python" \
         "py38 /opt/python/cp38-cp38/bin/python"; do
    set -- $i
    "$2" -m venv "$1"
    . "$1"/bin/activate
    pip install -r requirements.txt
    python setup.py bdist_wheel
    set +u; deactivate; set -u
done
