#!/usr/bin/env python3
import sys
import platform


def main():
    if platform.machine() == "i686":
        # Fix auditwheel.policy.get_arch_name() for i686.
        # https://github.com/benfogle/crossenv/issues/97

        # auditwheel < 6 uses globals.
        sys.maxsize = (2**31) - 1

        # auditwheel >= 6 removes globals, but introduces
        # struct.calcsize("P").

        def get_arch_name():
            return "i686"

        import auditwheel.policy

        auditwheel.policy.get_arch_name = get_arch_name

    import auditwheel.main

    sys.exit(auditwheel.main.main())


if __name__ == "__main__":
    main()
