#!/bin/sh
set -e -u -x

cd "$(dirname "$0")"/..
basedir=$PWD
[ -e configure ] || ./autogen.sh

python=$basedir/memtrace/python
uname=$(uname -s)-$(uname -m)
build=$python/build/$uname
tracer=$build/tracer
mkdir -p "$tracer"
cd "$tracer"
[ -e Makefile ] || "$basedir"/configure --prefix="$tracer/install"
nproc=$(getconf _NPROCESSORS_ONLN)
make -j"$nproc"
make -j"$nproc" install

cd "$python"
mkdir -p memtrace/tracer/"$uname"
(cd "$tracer"/install && tar -c \
     bin/valgrind \
     lib/valgrind/memtrace-* \
     lib/valgrind/vgpreload_core-*.so \
    ) | tar -C memtrace/tracer/"$uname" -xv
for python_version in cp36-cp36m cp37-cp37m cp38-cp38; do
    /opt/python/"$python_version"/bin/python -m venv "$build/$python_version"
    . "$build/$python_version"/bin/activate
    pip --disable-pip-version-check install -r requirements.txt
    python setup.py bdist_wheel
    set +u; deactivate; set -u
done
for whl in dist/*.whl; do
    auditwheel repair --wheel-dir=dist/wheelhouse "$whl"
done
