#!/usr/bin/env python3
from argparse import ArgumentParser
from datetime import datetime
import os
import subprocess

from config import load_config


def main():
    parser = ArgumentParser()
    parser.add_argument("--deploy")
    args, rest = parser.parse_known_args()
    basedir = os.path.dirname(__file__)
    rev = (
        subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=basedir,
        )
        .strip()
        .decode()
    )
    date = datetime.now().strftime("%Y-%m-%d")
    for arch, _ in load_config().arches:
        tag = f"mephi42/memtrace-build-{arch}:{date}-{rev}"
        docker_build_args = [
            "docker",
            "build",
            f"--tag={tag}",
            f"--target=final-{arch}",
            os.path.join(basedir, "image"),
        ]
        subprocess.check_call(docker_build_args + rest)
        if args.deploy:
            subprocess.check_call(["docker", "push", tag])


if __name__ == "__main__":
    main()
