#!/usr/bin/env python3
from argparse import ArgumentParser
from datetime import datetime
import os
import subprocess


def main():
    parser = ArgumentParser()
    args, rest = parser.parse_known_args()
    basedir = os.path.dirname(__file__)
    rev = (
        subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=basedir,
        )
        .strip()
        .decode()
    )
    date = datetime.now().strftime("%Y-%m-%d")
    tag = f"mephi42/memtrace-build:{date}-{rev}"
    docker_build_args = [
        "docker",
        "build",
        os.path.join(basedir, "image"),
        "-t",
        tag,
    ]
    subprocess.check_call(docker_build_args + rest)
    subprocess.check_call(["docker", "push", tag])


if __name__ == "__main__":
    main()
